addSbtPlugin("com.geirsson"              % "sbt-ci-release"         % "1.5.7")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"        % "0.9.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"           % "0.1.20")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"               % "2.2.21")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"           % "2.4.2")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"          % "1.8.2")
addSbtPlugin("org.jmotor.sbt"            % "sbt-dependency-updates" % "1.2.2")
